export const categoryImages: Record<string, string> = {
    abrasivos: '/categoriasimgs/abrasivos.png',
    aerosoles: '/categoriasimgs/aerosoles.png',
    agro: '/categoriasimgs/agro.png',
    automotriz: '/categoriasimgs/automotriz.png',
    bioseguridad: '/categoriasimgs/bioseguridad.png',
    cables_y_electricos: '/categoriasimgs/cables-electricos.png',
    cadenas_guayas_y_tensores: '/categoriasimgs/cadenas-guayas.png',
    cerrajeria_chapas_y_candados: '/categoriasimgs/cerrajeria.png',
    construccion: '/categoriasimgs/construccion.png',
    consumibles_brocas_y_discos: '/categoriasimgs/consumibles.png',
    electronica: '/categoriasimgs/electronica.png',
    escaleras: '/categoriasimgs/escaleras.png',
    grameras: '/categoriasimgs/grameras.png',
    herrajes: '/categoriasimgs/herrajes.png',
    herramienta_electrica: '/categoriasimgs/herramienta-electrica.png',
    herramienta_manual: '/categoriasimgs/herramienta-manual.png',
    herramienta_neumatica: '/categoriasimgs/herramienta-neumatica.png',
    hogar_y_cajas_herramientas: '/categoriasimgs/hogar-cajas.png',
    iluminacion: '/categoriasimgs/iluminacion.png',
    pinturas_solventes: '/categoriasimgs/pinturas-solventes.png',
    plomeria_y_griferias: '/categoriasimgs/plomeria.png',
    rodachines: '/categoriasimgs/rodachines.png',
    seguridad_industrial: '/categoriasimgs/seguridad-industrial.png',
    siliconas_y_adhesivos_cintas: '/categoriasimgs/siliconas.png',
    tomas_interruptores_tacos_y_clavijas: '/categoriasimgs/tomas-interruptores.png',
    tornilleria: '/categoriasimgs/tornilleria.png',
    
  };
  